# This workflow automatically copies labels from linked issues to pull requests.
# Reference: https://github.com/marketplace/actions/copy-issue-labels

name: Copy Issue Labels to PR
permissions:
  issues: write
  pull-requests: write

on: 
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
